spring.application.name=donatehub

# MySQL Database Configuration
# These will use environment variables in production, or fall back to your local settings for development.
spring.datasource.url=jdbc:mysql://mysql-1d141808-navaneethchowdary1234-70cc.b.aivencloud.com:23858/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_BTW2QFakafkUsjh1k_S

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8081}
management.endpoints.web.exposure.include=*

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME:noreply.donatehub@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:dwrkvemnargqjzcy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000

# Frontend URL (For CORS)
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}
